name: Generate Manifest

on:
  workflow_dispatch: # Allow manual trigger
  repository_dispatch:
    types: [firmware-release]

concurrency:
  group: gen-manifest
  cancel-in-progress: true

jobs:
  gen-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run gen manifest script
        run: python gen_manifest.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add firmware/ manifest/ manifests.json tag_latest.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update firmware binaries and manifest" && git push)
